plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.mobilnekt1'
    compileSdk 33

    defaultConfig {
        applicationId 'com.example.mobilnekt1'
        minSdk 23
        targetSdk 33
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
